### ISSUE TITLE
Unable to open modeler screen

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-bpm-public#14]
Unexpected error occurs while open modeler
```
io.jmix.core.DevelopmentException: Unable to find an instance of type 'interface org.slf4j.Logger' named 'log' for instance of 'io.jmix.bpmui.screen.modeler.BpmnModelerScreen'
	at io.jmix.ui.sys.UiControllerDependencyInjector.doInjection(UiControllerDependencyInjector.java:487)
	at io.jmix.ui.sys.UiControllerDependencyInjector.injectValues(UiControllerDependencyInjector.java:274)
	at io.jmix.ui.sys.UiControllerDependencyInjector.inject(UiControllerDependencyInjector.java:111)
	at io.jmix.ui.sys.UiControllerDependencyManager.inject(UiControllerDependencyManager.java:61)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:212)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:145)
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:306)
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:242)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257)
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587)
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

It seems that it comes after chnages from https://github.com/Haulmont/jmix-bpm-public/issues/13

**Comment by artemy63** [comment]
Root cause of such behavior is https://github.com/Haulmont/jmix-ui/issues/474
