### ISSUE TITLE
Cannot create "service" type task in design-time

### ISSUE THREAD

**Issue by belyaev-andrey** [Haulmont/jmix-bpm-public#39]
Jmix version: 1.0.0
Jmix Studio plugin version: 1.0.NIGHTLY620-211
IntelliJ version: IntelliJ IDEA 2021.1.2 (Ultimate Edition)

IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on June 1, 2021
Runtime version: 11.0.11+9-b1341.57 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8096M
Cores: 4
Non-Bundled Plugins: com.github.leomillon.uuidgenerator (4.4.1), com.github.oowekyala.javacc (1.8), org.intellij.RegexpTester (1.0.8), org.jetbrains.kotlin (211-1.5.20-release-284-IJ7442.40), com.intellij.lang.jsgraphql (2.9.1), io.jmix.studio (1.0.NIGHTLY620-211), org.asciidoctor.intellij.asciidoc (0.33.3)
Kotlin: 211-1.5.20-release-284-IJ7442.40

Frontend module installed.

STR: [See video](https://user-images.githubusercontent.com/5458814/123672369-e61efc00-d847-11eb-8663-cb30053b0316.mp4)

ER: Can create service task

AR: Application doesn't start:

```
org.flowable.common.engine.api.FlowableException: Errors while parsing:
[Validation set: 'flowable-executable-process' | Problem: 'flowable-servicetask-missing-implementation'] : One of the attributes 'class', 'delegateExpression', 'type', 'operation', or 'expression' is mandatory on serviceTask. - [Extra info : processDefinitionId = test-bpmn | processDefinitionName = Test-bpmn |  | id = Activity_1karszz |  | activityName = Service Task | ] ( line: 12, column: 60)

	at org.flowable.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:177) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.bpmn.deployer.ParsedDeploymentBuilder.createBpmnParseFromResource(ParsedDeploymentBuilder.java:97) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.bpmn.deployer.ParsedDeploymentBuilder.build(ParsedDeploymentBuilder.java:55) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.bpmn.deployer.BpmnDeployer.deploy(BpmnDeployer.java:78) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.persistence.deploy.DeploymentManager.deploy(DeploymentManager.java:62) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.cmd.DeployCmd.executeDeploy(DeployCmd.java:135) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:70) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:45) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:59) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:107) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:81) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:64) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:26) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:83) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.spring.SpringTransactionInterceptor.lambda$execute$0(SpringTransactionInterceptor.java:57) ~[flowable-spring-common-6.6.0.jar:6.6.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:57) ~[flowable-spring-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.RepositoryServiceImpl.deploy(RepositoryServiceImpl.java:99) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.engine.impl.repository.DeploymentBuilderImpl.deploy(DeploymentBuilderImpl.java:206) ~[flowable-engine-6.6.0.jar:6.6.0]
	at org.flowable.spring.configurator.DefaultAutoDeploymentStrategy.deployResourcesInternal(DefaultAutoDeploymentStrategy.java:65) ~[flowable-spring-6.6.0.jar:6.6.0]
	at org.flowable.spring.configurator.DefaultAutoDeploymentStrategy.deployResourcesInternal(DefaultAutoDeploymentStrategy.java:32) ~[flowable-spring-6.6.0.jar:6.6.0]
	at org.flowable.common.spring.CommonAutoDeploymentStrategy.deployResources(CommonAutoDeploymentStrategy.java:87) ~[flowable-spring-common-6.6.0.jar:6.6.0]
	at org.flowable.spring.SpringProcessEngineConfiguration.autoDeployResources(SpringProcessEngineConfiguration.java:124) ~[flowable-spring-6.6.0.jar:6.6.0]
	at org.flowable.spring.SpringProcessEngineConfiguration.lambda$start$0(SpringProcessEngineConfiguration.java:223) ~[flowable-spring-6.6.0.jar:6.6.0]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at org.flowable.spring.SpringProcessEngineConfiguration.start(SpringProcessEngineConfiguration.java:220) ~[flowable-spring-6.6.0.jar:6.6.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.8.jar:5.3.8]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.1.jar:2.5.1]
	at com.company.bpmtest1.BpmTest1Application.main(BpmTest1Application.java:25) ~[main/:na]
```

**Comment by belyaev-andrey** [comment]
Will be moved to Jmix Studio bugtracker
