### ISSUE TITLE
 util.DeprecatedMethodException in logs 

### ISSUE THREAD

**Issue by konyashkina** [Haulmont/jmix-bpm-public#45]
A lot of `util.DeprecatedMethodException` warnings in logs. 

Jmix version: 1.0.0
Jmix Studio plugin version: 1.0.1-212
IntelliJ version: IntelliJ IDEA 2021.2 (Ultimate Edition)

**Steps to reproduce:**
(Pre-requisites: BPM add-on installed. Jmix application started.
1. Open the app in browser, log in as default user.
2. Open Modeler, create a Task with Call Activity.
3. Look into IDEA log. 

**AR:** 
2021-08-03 14:40:23,443 [ 996243]   WARN - util.DeprecatedMethodException - The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. 
A proper @NotNull implementation required com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.**CubaWelcomeScreenEditor**'. A proper @NotNull implementation required
	at com.intellij.util.DeprecatedMethodException.reportDefaultImplementation(DeprecatedMethodException.java:33)

 **A proper @NotNull implementation required' was reported 50 times**

`2021-08-03 16:02:58,489 [5951289]   WARN - util.DeprecatedMethodException - Exception 'com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. A proper @NotNull implementation required' was reported 10 times 
2021-08-03 16:02:58,578 [5951378]   WARN - util.DeprecatedMethodException - Exception 'com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. A proper @NotNull implementation required' was reported 20 times 
2021-08-03 16:02:58,743 [5951543]   WARN - util.DeprecatedMethodException - Exception 'com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. A proper @NotNull implementation required' was reported 30 times 
2021-08-03 16:02:58,840 [5951640]   WARN - util.DeprecatedMethodException - Exception 'com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. A proper @NotNull implementation required' was reported 40 times 
2021-08-03 16:02:58,983 [5951783]   WARN - util.DeprecatedMethodException - Exception 'com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. A proper @NotNull implementation required' was reported 50 times `

`2021-08-03 15:46:27,856 [4960656]   WARN - util.DeprecatedMethodException - The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. A proper @NotNull implementation required 
com.intellij.util.DeprecatedMethodException: The default implementation of method 'com.intellij.openapi.fileEditor.FileEditor.getFile' is deprecated, you need to override it in 'class com.haulmont.jmixstudio.intellij.welcome.CubaWelcomeScreenEditor'. A proper @NotNull implementation required
	at com.intellij.util.DeprecatedMethodException.reportDefaultImplementation(DeprecatedMethodException.java:33)
	at com.intellij.openapi.fileEditor.FileEditor.getFile(FileEditor.java:133)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.getSelectedEditors(DaemonCodeAnalyzerImpl.java:1001)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl$UpdateRunnable.run(DaemonCodeAnalyzerImpl.java:860)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by gorbunkov** [comment]
The issue is for the CUBA Studio IntelliJ Plugin. The issue must be placed into the Studio issues tracker.
