### ISSUE TITLE
Exception when changing the order of input dialog parameters in the modeler

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-bpm-public#48]
Open the modeler screen
Add the User Task element
Select the input dialog form type
Add several input dialog parameters
Select any of them and try to move it up or down using the proper button

AR:
The exception:
```
Caused by: java.lang.IllegalArgumentException: entity or id is null
	at io.jmix.core.common.util.Preconditions.checkNotNullArgument(Preconditions.java:101) ~[jmix-core-1.0.1.jar:na]
	at io.jmix.ui.model.impl.CollectionContainerImpl.getItemIndex(CollectionContainerImpl.java:126) ~[jmix-ui-1.0.1.jar:na]
	at io.jmix.ui.model.impl.CollectionContainerImpl.getItemOrNull(CollectionContainerImpl.java:120) ~[jmix-ui-1.0.1.jar:na]
	at io.jmix.ui.component.data.table.ContainerTableItems.getItem(ContainerTableItems.java:96) ~[jmix-ui-1.0.1.jar:na]
	at io.jmix.ui.component.impl.AbstractTable.setSelected(AbstractTable.java:420) ~[jmix-ui-1.0.1.jar:na]
	at io.jmix.ui.component.impl.AbstractTable.setSelected(AbstractTable.java:404) ~[jmix-ui-1.0.1.jar:na]
	at io.jmix.bpmui.screen.modeler.properties.ModelerPropsPanelUiHelper.moveTableItemUp(ModelerPropsPanelUiHelper.java:82) ~[jmix-bpm-ui-1.0.1.jar:na]
	at io.jmix.bpmui.screen.modeler.properties.formdata.FormDataPropertiesFragment.onFormFieldsTableMoveFieldUpActionPerformed(FormDataPropertiesFragment.java:344) ~[jmix-bpm-ui-1.0.1.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-1.0.1.jar:na]
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220) ~[jmix-ui-1.0.1.jar:na]
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75) ~[jmix-ui-1.0.1.jar:na]
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77) ~[jmix-ui-1.0.1.jar:na]
	at com.vaadin.ui.Button$1.click(Button.java:57) ~[vaadin-server-8.12.3-3-jmix.jar:8.12.3-3-jmix]
	... 87 common frames omitted
```

**Comment by maistrenkoIulia** [comment]
verified
